var annotated_dup =
[
    [ "AbstractController", "d5/da2/class_abstract_controller.html", "d5/da2/class_abstract_controller" ],
    [ "AddNewPatientController", "d0/d03/class_add_new_patient_controller.html", "d0/d03/class_add_new_patient_controller" ],
    [ "AddNewTherapistController", "d8/d72/class_add_new_therapist_controller.html", "d8/d72/class_add_new_therapist_controller" ],
    [ "BucketsTriggers", "d4/d05/class_buckets_triggers.html", "d4/d05/class_buckets_triggers" ],
    [ "CalibrationManager", "d9/d80/class_calibration_manager.html", "d9/d80/class_calibration_manager" ],
    [ "EditPatientDetailsController", "da/d0d/class_edit_patient_details_controller.html", "da/d0d/class_edit_patient_details_controller" ],
    [ "EditTherapistDetailsController", "d7/dd4/class_edit_therapist_details_controller.html", "d7/dd4/class_edit_therapist_details_controller" ],
    [ "FloatTextController", "de/ddc/class_float_text_controller.html", "de/ddc/class_float_text_controller" ],
    [ "HandInteraction", "db/d46/class_hand_interaction.html", "db/d46/class_hand_interaction" ],
    [ "LoginController", "d5/dc9/class_login_controller.html", "d5/dc9/class_login_controller" ],
    [ "MailsSystemManager", "df/de5/class_mails_system_manager.html", null ],
    [ "MainController", "d9/d0b/class_main_controller.html", "d9/d0b/class_main_controller" ],
    [ "MessageController", "d7/dde/class_message_controller.html", "d7/dde/class_message_controller" ],
    [ "PatientController", "d7/d29/class_patient_controller.html", "d7/d29/class_patient_controller" ],
    [ "PauseScript", "d6/d03/class_pause_script.html", "d6/d03/class_pause_script" ],
    [ "PinchGrabable", "d5/d3d/class_pinch_grabable.html", "d5/d3d/class_pinch_grabable" ],
    [ "PinchGrabber", "d9/d6a/class_pinch_grabber.html", "d9/d6a/class_pinch_grabber" ],
    [ "PinchManager", "d5/d32/class_pinch_manager.html", "d5/d32/class_pinch_manager" ],
    [ "PlayerHeight", "de/dc5/class_player_height.html", null ],
    [ "QuestFileManager", "df/dd8/class_quest_file_manager.html", null ],
    [ "QuitApplicationController", "de/db3/class_quit_application_controller.html", "de/db3/class_quit_application_controller" ],
    [ "ReportsManager", "d5/d3c/class_reports_manager.html", null ],
    [ "ScenesMusicHandler", "da/da3/class_scenes_music_handler.html", null ],
    [ "SearchPatientController", "da/d23/class_search_patient_controller.html", "da/d23/class_search_patient_controller" ],
    [ "Settings", "db/d2b/class_settings.html", "db/d2b/class_settings" ],
    [ "SettingsController", "d8/d2f/class_settings_controller.html", "d8/d2f/class_settings_controller" ],
    [ "StartCalibration", "d4/d20/class_start_calibration.html", null ],
    [ "TherapistController", "de/dad/class_therapist_controller.html", "de/dad/class_therapist_controller" ],
    [ "TherapyData", "d2/d46/class_therapy_data.html", "d2/d46/class_therapy_data" ],
    [ "TherapyManager", "d3/d6d/class_therapy_manager.html", "d3/d6d/class_therapy_manager" ],
    [ "TimerScirpt", "d1/d04/class_timer_scirpt.html", null ],
    [ "ViewPatientDetailsController", "dd/da6/class_view_patient_details_controller.html", "dd/da6/class_view_patient_details_controller" ],
    [ "ViewTherapistDetailsController", "da/db2/class_view_therapist_details_controller.html", "da/db2/class_view_therapist_details_controller" ]
];